### PR TITLE
update examples and explanations for module 1_2

### PR DESCRIPTION
**Pull request by sb1752**
Updated the examples, added rust playground links and added some language to help clarify *move* vs *copy*

### CODE REVIEW

**Comment by delcin-raj** [comment]
The issue I have with your explanation about move is that in Rust it applies for values of types which are stored in Stack also, if they did not implement Copy trait.

The move semantics is quite tricky in the sense when you have an array [u8;10] for example which is initialised in the stack and you are moving it to a function by calling it, then the entire array is copied into that called function's stack frame.

So even in move semantics the values which are stored in the stack are getting copied to a different stack frame, while the data in heap is not copied.

**Comment by sb1752** [comment]
Right. Isn't this what I say? `Any type that *owns* data on the heap is typically *moved* instead of *copied*.` An array doesn't own data on the heap. It's entirely stack allocated. 

I'll make this more clear and update the explanation.

**Comment by delcin-raj** [comment]
Yes, but it's kind of confusing to students who don't know the context very well.

So let's say this explicitly!

Also Rust books don't make this runtime mechanics explicit.

And this is one of the use case of Box types, where you can wrap an array or large structs in Box so that it won't be copied at every function call.

**Comment by sb1752** [comment]
How does this sound? Feel free to edit

```
Any type that *owns* data on the heap is typically *moved*.
In this case, a *String* is actually a *smart pointer* to heap data which stores UTF-8 valid bytes.
So when the pointer is passed as an argument, ownership of the heap data is moved from the variable in `main` to the variable `s` in `calculate_length`.
A new copy of the pointer is being made in `calculate_length` and then ownership of the heap data is given to that new pointer.
In Rust, only one variable can have ownership of heap data at any given time.
This concept of a single owner is how Rust efficiently manages memory.
Whenever that owner goes out of scope, Rust knows that it can safely clear the data owned in memory as well.
```

**Comment by delcin-raj** [comment]
Perfect!

**Comment by sb1752** [comment]
Updated

**Pull request merged**
